# Generated by Django 5.2.9 on 2025-12-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='katakanaword',
            name='romaji',
            field=models.CharField(default='', max_length=100),
        ),
    ]
